from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 250, 200))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonNewbie = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonNewbie.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButtonNewbie)
        self.radioButtonAmateur = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonAmateur.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButtonAmateur)
        self.radioButtonProfessional = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonProfessional.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButtonProfessional)
        self.radioButtonCustom = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonCustom.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButtonCustom)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditWidth = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditWidth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditWidth.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineEditWidth.setFixedWidth(50)
        self.lineEditWidth.setEnabled(False)
        self.lineEditWidth.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEditWidth)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditHeight = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditHeight.setFixedWidth(50)
        self.lineEditHeight.setEnabled(False)
        self.lineEditHeight.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEditHeight)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditColors = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditColors.setFixedWidth(50)
        self.lineEditColors.setEnabled(False)
        self.lineEditColors.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEditColors)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.radioButtonNewbie.setText(_translate("MainWindow", "Новичок (8x8 4 цвета)"))
        self.radioButtonAmateur.setText(_translate("MainWindow", "Любитель (12x12 6 цветов)"))
        self.radioButtonProfessional.setText(_translate("MainWindow", "Профессионал (20x20 10 цветов)"))
        self.radioButtonCustom.setText(_translate("MainWindow", "Пользовательский"))
        self.label.setText(_translate("MainWindow", "Ширина 4-30"))
        self.label_2.setText(_translate("MainWindow", "Высота 4-30"))
        self.label_3.setText(_translate("MainWindow", "Кол-во цветов 3-10"))
